version: "3"

services:
  asgard-api:
    build: ./api
    container_name: a2-asgard-api
    restart: always
    networks:
      - asgard_internal
      - proxy
    env_file:
      - .env
    depends_on:
      - db
      - mqtt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asgard-api.rule=Host(`asgard.localhost`) && PathPrefix(`/v2`)"
      - "traefik.http.routers.asgard-api.entrypoints=https"
      - "traefik.http.routers.asgard-api.tls=true"
      - "traefik.http.services.asgard-api.loadbalancer.server.port=3000"


  yggdrasil-web:
    build: ./yggdrasil-web
    container_name: a2-yggdrasil-web
    restart: always
    networks:
      - asgard_internal
      - proxy
    env_file:
      - .env
    depends_on:
      - asgard-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yggdrasil-web.rule=Host(`yggdrasil.localhost`)"
      - "traefik.http.routers.yggdrasil-web.entrypoints=https"
      - "traefik.http.routers.yggdrasil-web.tls=true"
      - "traefik.http.services.yggdrasil-web.loadbalancer.server.scheme=http"
      - "traefik.http.services.yggdrasil-web.loadbalancer.server.port=80"

  asgard-admin:
    build: ./admin
    container_name: a2-asgard-admin
    restart: always
    networks:
      - asgard_internal
      - proxy
    depends_on:
      - asgard-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asgard-admin.rule=Host(`asgard.localhost`)"
      - "traefik.http.routers.asgard-admin.entrypoints=https"
      - "traefik.http.routers.asgard-admin.tls=true"
      - "traefik.http.services.asgard-admin.loadbalancer.server.scheme=http"
      - "traefik.http.services.asgard-admin.loadbalancer.server.port=80"

  db:
    container_name: a2-asgard-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - asgard_internal
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  mqtt:
    image: eclipse-mosquitto:2
    container_name: a2-asgard-mqtt
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    stdin_open: true
    tty: true
    networks:
      - asgard_internal
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  mysql-data:
  mqtt-data:
  mqtt-log:

networks:
  asgard_internal:
  proxy:
    external: true
