version: "3"

services:
  api:
    build: ./api
    container_name: asgard-api
    restart: always
    networks:
      - asgard_internal
    env_file:
      - .env
    ports:
     - 9001:3000
    depends_on:
     - db

  yggdrasil-web:
    build: ./yggdrasil-web
    container_name: yggdrasil-web
    restart: always
    networks:
      - asgard_internal
    env_file:
      - .env
    ports:
     - 4444:80

  admin-web:
    build: ./admin-web
    container_name: admin-web
    restart: always
    networks:
      - asgard_internal
    environment:
    - VITE_API_BASE_URL=http://localhost:9001
    ports:
     - 1337:80
    depends_on:
     - api

  db:
    container_name: asgard-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    # network_mode: service:db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - asgard_internal
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  mqtt:
    image: eclipse-mosquitto:2
    container_name: asgard-mqtt
    volumes:
      - ../../mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    stdin_open: true 
    tty: true
    networks:
      - asgard_internal
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  mysql-data:

networks:
  asgard_internal: