apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "asgard.fullname" . }}-env
  labels:
    {{- include "asgard.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ tpl (printf "%v" $value) $ | quote }}
{{- end }}
