apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "asgard.fullname" . }}-mysql-data
  labels:
    {{- include "asgard.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
