apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asgard.fullname" . }}-secret-env
  labels:
    {{- include "asgard.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ tpl (printf "%v" $value) $ | quote }}
{{- end }}
