apiVersion: v1
kind: Service
metadata:
  name: {{ include "asgard.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "asgard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "asgard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "asgard.fullname" . }}-admin
  labels:
    app.kubernetes.io/component: admin
    {{- include "asgard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  selector:
    {{- include "asgard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  ports:
    - name: http
      port: {{ .Values.admin.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "asgard.fullname" . }}-db
  labels:
    app.kubernetes.io/component: db
    {{- include "asgard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  selector:
    {{- include "asgard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
  ports:
    - name: mysql
      port: {{ .Values.db.service.port }}
      targetPort: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "asgard.fullname" . }}-mqtt
  labels:
    app.kubernetes.io/component: mqtt
    {{- include "asgard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mqtt.service.type }}
  selector:
    {{- include "asgard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt
  ports:
    - name: mqtt
      port: {{ .Values.mqtt.service.port }}
      targetPort: mqtt
    - name: websockets
      port: {{ .Values.mqtt.websocketPort }}
      targetPort: websockets
