services:
  app:
    container_name: asgard-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 20
    volumes:
      - ..:/workspace:cached
    command: sleep infinity # Overrides default command so things don't shut down after the process ends.
    networks:
      - asgard-dev

  db:
    image: mysql:8.0
    container_name: asgard-db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: computing
      MYSQL_DATABASE: asgard
      MYSQL_USER: asgard
      MYSQL_PASSWORD: computing
    networks:
      - asgard-dev

  mqtt:
    image: eclipse-mosquitto
    container_name: asgard-mqtt
    volumes:
      - ../../mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    stdin_open: true 
    tty: true
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - asgard-dev

volumes:
  mysql-data:
  mqtt-data:
  mqtt-log:

networks:
  asgard-dev: